### ISSUE TITLE
Updates on subboard checklist is not reflected on main board

### ISSUE THREAD

**Issue by msgre** [SkyPicker/Trelolo#16]
If there is already checked item in "Issues" checklist on some card on Main board, and I will update items on original card (for example add new items, delete some of them, change state), state on related card on Main board is not updated.

**Comment by bolkaaa** [comment]
This should have been already solved (feat/issue_15)

**Comment by msgre** [comment]
There is edge case which doesn't work:

* ✅ Create `{tag1} item1` on subboard, add there checklist with 3 items (a, b, c)
* ✅ Mark all three items -> card will be moved to second column on main board and marked as solved
* ✅ Add new item "d" on original `{tag1} item1` card and *leave in unchecked* -> card will be moved back to first column on main board, unmarked as solved
* ❌ Delete item "d" on original cart -> nothing happened (should be moved to second column an again marked as solved)
