### ISSUE TITLE
Card not moved into IN PROGRESS column

### ISSUE THREAD

**Issue by msgre** [SkyPicker/Trelolo#20]
When original card have some checklist, and some item is marked as solved (checked), copy of card on Main board stay in first column (but should be moved into second "IN PROGRESS" column).

When I check all chechlist items as solved, then card is moved into second column (but I suppose it should be moved from second to third, named probably "DONE"?)

**Comment by msgre** [comment]
Maybe regression after https://github.com/SkyPicker/Trelolo/issues/15?

**Comment by bolkaaa** [comment]
Moving card into the third column was disabled... (specification)

**Comment by msgre** [comment]
Ok (about third column). And what is current specification please?

I asking you because I don't understand to one current behaviour:

* if I have card on subboard with list of items, and every item is unchecked, card stay in first column on main board
* if i check any item on my subboard card, i suppose that it should be moved to second column on main board

Am I right? What represent that 2 columns on main board? I suppose that first one is "TODO" and second "IN PROGRESS" (so if I mark on my card that something is done, we are in progress).

Or do you move cards on main board on other action? (like moving card on subboard between columns)
